export const CNAE_LIST = [
  { code: '6435201', desc: 'Sociedades de crédito imobiliário' },
  { code: '6435202', desc: 'Associações de poupança e empréstimo' },
  { code: '6435203', desc: 'Companhias hipotecárias' },
  { code: '6436100', desc: 'Sociedades de crédito, financiamento e investimento - financeiras' },
  { code: '6437900', desc: 'Sociedades de crédito ao microempreendedor' },
  { code: '6438799', desc: 'Outras instituições de intermediação não-monetária (Inclui ESC)' },
  { code: '6440900', desc: 'Arrendamento mercantil (Leasing)' },
  { code: '6450600', desc: 'Sociedades de capitalização' },
  { code: '6461100', desc: 'Holdings de instituições financeiras' },
  { code: '6462000', desc: 'Holdings de instituições não-financeiras' },
  { code: '6463800', desc: 'Outras sociedades de participação, exceto holdings' },
  { code: '6470101', desc: 'Fundos de investimento, exceto previdenciários e imobiliários' },
  { code: '6470102', desc: 'Fundos de investimento previdenciários' },
  { code: '6470103', desc: 'Fundos de investimento imobiliários' },
  { code: '6491300', desc: 'Sociedades de fomento mercantil - factoring' },
  { code: '6492100', desc: 'Securitização de créditos' },
  { code: '6493000', desc: 'Administração de consórcios para aquisição de bens e direitos' },
  { code: '6499901', desc: 'Clubes de investimento' },
  { code: '6499902', desc: 'Sociedades de investimento a capital fixo' },
  { code: '6499903', desc: 'Fundo garantidor de crédito' },
  { code: '6499904', desc: 'Caixas de financiamento de corporações' },
  { code: '6499905', desc: 'Concessão de crédito por parte de IF não financeiras' },
  { code: '6511101', desc: 'Sociedade seguradora de seguros vida' },
  { code: '6511102', desc: 'Planos de auxílio-funeral' },
  { code: '6512000', desc: 'Sociedade seguradora de seguros não vida' },
  { code: '6520100', desc: 'Sociedade seguradora de seguros saúde' },
  { code: '6530800', desc: 'Resseguros' },
  { code: '6541300', desc: 'Previdência complementar fechada' },
  { code: '6542100', desc: 'Previdência complementar aberta' },
  { code: '6550200', desc: 'Planos de saúde' },
  { code: '6612601', desc: 'Corretoras de títulos e valores mobiliários' },
  { code: '6612602', desc: 'Distribuidoras de títulos e valores mobiliários' },
  { code: '6612603', desc: 'Corretoras de câmbio' },
  { code: '6612604', desc: 'Corretoras de contratos de mercadorias' },
  { code: '6612605', desc: 'Agentes de investimentos em aplicações financeiras (AAI)' },
  { code: '6613400', desc: 'Administração de cartões de crédito' },
  { code: '6619301', desc: 'Serviços de liquidação e custódia' },
  { code: '6619302', desc: 'Correspondentes de instituições financeiras' },
  { code: '6619305', desc: 'Operadoras de cartões de débito' },
  { code: '6621501', desc: 'Peritos e avaliadores de seguros' },
  { code: '6621502', desc: 'Auditoria e consultoria atuarial' },
  { code: '6622300', desc: 'Corretores e agentes de seguros, previdência e saúde' },
  { code: '6629100', desc: 'Atividades auxiliares dos seguros, previdência e saúde n.e.' },
  { code: '6630400', desc: 'Atividades de administração de fundos por contrato ou comissão' },
  { code: '6611801', desc: 'Bolsa de valores' },
  { code: '6611802', desc: 'Bolsa de mercadorias' },
  { code: '6611803', desc: 'Bolsa de mercadorias e futuros' },
  { code: '6611804', desc: 'Administração de mercados de balcão organizados' },
  { code: '6619303', desc: 'Representações de bancos estrangeiros' },
  { code: '6619304', desc: 'Caixas eletrônicos' },
  { code: '6619399', desc: 'Outras ativ. auxiliares serv. financeiros (Fintechs/Pagamentos)' }
];

export const NATUREZA_JURIDICA_LIST = [
  "206-2 - Sociedade Empresária Limitada",
  "213-5 - Empresário (Individual)",
  "230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)",
  "204-6 - Sociedade Anônima Aberta",
  "205-4 - Sociedade Anônima Fechada",
  "201-1 - Empresa Pública",
  "203-8 - Sociedade de Economia Mista",
  "399-9 - Associação Privada",
  "306-9 - Fundação Privada",
  "330-1 - Organização Social (OS)",
  "214-3 - Cooperativa",
  "223-2 - Sociedade Simples Pura",
  "224-0 - Sociedade Simples Limitada",
  "225-9 - Sociedade Simples em Nome Coletivo",
  "226-7 - Sociedade Simples em Comandita Simples"
];